export const icons = {
  facebook: require('~/renderer/resources/icons/facebook.svg'),
  youtube: require('~/renderer/resources/icons/youtube.svg'),
  menu: require('~/renderer/resources/icons/menu.svg'),
  location: require('~/renderer/resources/icons/location.svg'),
  locationOutline: require('~/renderer/resources/icons/location-outline.svg'),
  replacement: require('~/renderer/resources/icons/replacement.svg'),
  plan: require('~/renderer/resources/icons/plan.svg'),
  register: require('~/renderer/resources/icons/register.svg'),
  news: require('~/renderer/resources/icons/news.svg'),
  newsPaper: require('~/renderer/resources/icons/news-paper.svg'),
  group: require('~/renderer/resources/icons/group.svg'),
  document: require('~/renderer/resources/icons/document.svg'),
  history: require('~/renderer/resources/icons/history.svg'),
  info: require('~/renderer/resources/icons/info.svg'),
  trophy: require('~/renderer/resources/icons/trophy.svg'),
  user: require('~/renderer/resources/icons/user.svg'),
  userShield: require('~/renderer/resources/icons/user-shield.svg'),
  money: require('~/renderer/resources/icons/money.svg'),
  userQuestion: require('~/renderer/resources/icons/user-question.svg'),
  chevron: require('~/renderer/resources/icons/chevron.svg'),
  chevronDouble: require('~/renderer/resources/icons/chevron-double.svg'),
  email: require('~/renderer/resources/icons/email.svg'),
  search: require('~/renderer/resources/icons/search.svg'),
  drop: require('~/renderer/resources/icons/drop.svg'),
  banner: require('~/renderer/resources/icons/banner.svg'),
};
