export const icons = {
  facebook: require('~/renderer/resources/icons/facebook.svg'),
  youtube: require('~/renderer/resources/icons/youtube.svg'),
  menu: require('~/renderer/resources/icons/menu.svg'),
  location: require('~/renderer/resources/icons/location.svg'),
  replacement: require('~/renderer/resources/icons/replacement.svg'),
  plan: require('~/renderer/resources/icons/plan.svg'),
  register: require('~/renderer/resources/icons/register.svg'),
  news: require('~/renderer/resources/icons/news.svg'),
  newsPaper: require('~/renderer/resources/icons/news-paper.svg'),
  group: require('~/renderer/resources/icons/group.svg'),
  document: require('~/renderer/resources/icons/document.svg'),
  history: require('~/renderer/resources/icons/history.svg'),
  info: require('~/renderer/resources/icons/info.svg'),
  trophy: require('~/renderer/resources/icons/trophy.svg'),
}
