export const icons = {
  facebook: require('~/renderer/resources/icons/facebook.svg'),
  youtube: require('~/renderer/resources/icons/youtube.svg'),
  menu: require('~/renderer/resources/icons/menu.svg'),
  location: require('~/renderer/resources/icons/location.svg'),
  locationOutline: require('~/renderer/resources/icons/location-outline.svg'),
  replacement: require('~/renderer/resources/icons/replacement.svg'),
  plan: require('~/renderer/resources/icons/plan.svg'),
  register: require('~/renderer/resources/icons/register.svg'),
  chevron: require('~/renderer/resources/icons/chevron.svg'),
  drop: require('~/renderer/resources/icons/drop.svg'),
  banner: require('~/renderer/resources/icons/banner.svg'),
  close: require('~/renderer/resources/icons/close.svg'),
  link: require('~/renderer/resources/icons/link.svg'),
};
